[package]
name = "rust-solana-regex-example"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"

[dev-dependencies]
regex = "1.11.1"
solana-sdk = "1.18.26"


[profile.dev]
opt-level = 0
lto = "off"

[profile.release]
opt-level = 3
lto = "fat"
panic = "abort"
codegen-units = 1
